[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200
  force = true
  headers = { 
    Access-Control-Allow-Origin = "https://ytmuzic.netlify.app",
    Access-Control-Allow-Methods = "GET, POST, OPTIONS",
    Access-Control-Allow-Headers = "Content-Type"
  }
